# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Published_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
    ]
